#!/usr/bin/env bash

cd linux
cp ../pentium-m.config .config
make-kpkg clean
CONCURRENCY_LEVEL=`getconf _NPROCESSORS_ONLN` fakeroot make-kpkg --initrd  --revision=0.1 --append-to-version=-pentium-m-v1 kernel_image kernel_headers
cd ..
