#!/usr/bin/env bash

cd linux
make-kpkg clean
CONCURRENCY_LEVEL=`getconf _NPROCESSORS_ONLN` fakeroot make-kpkg --initrd  --revision=0.1 --append-to-version=-custom-pentium-m kernel_image kernel_headers
cd ..
